export const ROLES = {
    ADMIN: 'ADMINISTRADOR',
    SECURITY: 'OFICIAL_SEGURIDAD',
    STAFF: 'PERSONAL_ADMINISTRATIVO',
    STUDENT: 'ESTUDIANTE'
  };
  
export const PERMISSIONS = {
    CREATE_USER: 'create_user',
    DELETE_USER: 'delete_user',
    VIEW_DASHBOARD: 'view_dashboard',
    EDIT_PROFILE: 'edit_profile',
    VIEW_PUBLIC: 'view_public',
    VIEW_OCCUPATION: 'view_occupation',
    MANAGE_VEHICLES: 'manage_vehicles',
    MANAGE_PARKINGS: 'manage_parkings',
    VEHICLE_ENTRY_EXIT: 'vehicle_entry_exit',
    ACCESS_REPORTS: 'access_reports',
    SYSTEM_SETTINGS: 'system_settings',
    VIEW_LOGS: 'view_logs',
    CHECK_VEHICLES: 'check_vehicles'
};
  
// Role-permission mapping
export const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: [PERMISSIONS.CREATE_USER,
        PERMISSIONS.DELETE_USER,
        PERMISSIONS.VIEW_DASHBOARD,
        PERMISSIONS.EDIT_PROFILE,
        PERMISSIONS.VIEW_PUBLIC,
        PERMISSIONS.VIEW_OCCUPATION,
        PERMISSIONS.MANAGE_VEHICLES,
        PERMISSIONS.MANAGE_PARKINGS,
        PERMISSIONS.VEHICLE_ENTRY_EXIT,
        PERMISSIONS.ACCESS_REPORTS,
        PERMISSIONS.SYSTEM_SETTINGS,
        PERMISSIONS.VIEW_LOGS,
        PERMISSIONS.CHECK_VEHICLES],
        
    [ROLES.USER]: [
        PERMISSIONS.VIEW_DASHBOARD, 
        PERMISSIONS.EDIT_PROFILE, 
        PERMISSIONS.VIEW_PUBLIC,
        PERMISSIONS.VIEW_OCCUPATION
    ],
    [ROLES.STAFF]: [
        PERMISSIONS.VIEW_DASHBOARD, 
        PERMISSIONS.EDIT_PROFILE, 
        PERMISSIONS.VIEW_PUBLIC,
        PERMISSIONS.VIEW_OCCUPATION,
        PERMISSIONS.VEHICLE_ENTRY_EXIT,
        PERMISSIONS.ACCESS_REPORTS
    ],
    [ROLES.SECURITY]:[
        PERMISSIONS.VIEW_OCCUPATION,
        PERMISSIONS.VIEW_DASHBOARD,
        PERMISSIONS.VIEW_PUBLIC,
        PERMISSIONS.VEHICLE_ENTRY_EXIT,
        PERMISSIONS.CHECK_VEHICLES
    ]



};