export const ROLES = {
    ADMIN: 'admin',
    USER: 'user',
    STAFF: 'staff'
};
  
export const PERMISSIONS = {
    CREATE_USER: 'create_user',
    DELETE_USER: 'delete_user',
    VIEW_DASHBOARD: 'view_dashboard',
    EDIT_PROFILE: 'edit_profile',
    VIEW_PUBLIC: 'view_public',
    CHECK_VEHICLE: 'check_vehicle'
};
  

// Role-permission mapping
export const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: [PERMISSIONS.CREATE_USER, PERMISSIONS.DELETE_USER, PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.EDIT_PROFILE, PERMISSIONS.VIEW_PUBLIC, PERMISSIONS.CHECK_VEHICLE],
    [ROLES.USER]: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.EDIT_PROFILE, PERMISSIONS.VIEW_PUBLIC],
    [ROLES.STAFF]: [ PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.EDIT_PROFILE, PERMISSIONS.VIEW_PUBLIC, PERMISSIONS.CHECK_VEHICLE]
};